// Writes the ABIs, the known deployments and the seed agent configs into abis/ (for anyone) and into the app
// (app/src/generated, as TypeScript). Seed configs are copied byte for byte, so their hashes still match.
const fs = require("fs");
const path = require("path");
const config = require("../config/robinhood.json");

const ARTIFACTS = path.join(__dirname, "..", "artifacts", "src");
const ROOT = path.join(__dirname, "..", "..");
const OUT = path.join(ROOT, "abis");
const APP = path.join(ROOT, "app", "src", "generated");
const CONTRACTS = { AgentRegistry: "registryAbi", AgentMarket: "marketAbi", TokenOracle: "oracleAbi" };

fs.mkdirSync(OUT, { recursive: true });
fs.mkdirSync(APP, { recursive: true });
let ts = "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n";
for (const [name, exportName] of Object.entries(CONTRACTS)) {
  const { abi } = JSON.parse(fs.readFileSync(path.join(ARTIFACTS, `${name}.sol`, `${name}.json`), "utf8"));
  fs.writeFileSync(path.join(OUT, `${name}.json`), JSON.stringify(abi, null, 2) + "\n");
  ts += `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
fs.writeFileSync(path.join(APP, "abis.ts"), ts);

const deployments = {};
const dir = path.join(__dirname, "..", "deployments");
for (const f of ["robinhood.json", "localhost.json"]) {
  const p = path.join(dir, f);
  if (!fs.existsSync(p)) continue;
  const d = JSON.parse(fs.readFileSync(p, "utf8"));
  deployments[d.chainId] = d;
  if (f === "robinhood.json") fs.copyFileSync(p, path.join(OUT, "robinhood.json"));
}
fs.writeFileSync(
  path.join(APP, "deployments.ts"),
  "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n" +
    `type A = \`0x\${string}\`;
export type Deployment = {
  network: string;
  chainId: number;
  deployer: A;
  roles: { admin: A; guardian: A; keeper: A };
  timelock: A;
  treasury: A;
  oracle: A;
  registry: A;
  market: A;
  token: A | null;
  startBlock: number;
  deployBlock: number;
};

export const deployments: Record<number, Deployment> = ${JSON.stringify(deployments, null, 2)};\n`
);

const seeds = config.protocol.seeds.map(({ file, pricePerUseEth }) => ({
  file,
  pricePerUseEth,
  bytes: fs.readFileSync(path.join(__dirname, "..", "config", file), "utf8"),
}));
fs.writeFileSync(
  path.join(APP, "seeds.ts"),
  "// Generated by contracts/scripts/export-abis.js. Do not edit.\n// Exact file contents: keccak256 of `bytes` is the configHash written on-chain at deployment.\n\n" +
    `export const seeds: { file: string; pricePerUseEth: string; bytes: string }[] = ${JSON.stringify(seeds, null, 2)};\n\n` +
    `export const protocol = ${JSON.stringify({ chainId: config.network.chainId, explorer: config.network.explorer, pons: config.pons, deploymentFeeEth: config.protocol.deploymentFeeEth, oracle: config.protocol.oracle }, null, 2)} as const;\n`
);
console.log(`ABIs, deployments and seed configs written to abis/ and app/src/generated/`);
